apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-7gnj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-7gnj
    app.kubernetes.io/part-of: mc-unsupported-runtime
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-7gnj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-7gnj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-7gnj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lsgl-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-7gnj@sha256:d06507ba47bcfa56d56cd82720a139cf2e830ca1f7c2eef5d8ad17441a9ae9ce
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
